/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PracticeSupportsRouteImport } from './routes/practice-supports'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdvocacyRouteImport } from './routes/advocacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSupportsRoute = PracticeSupportsRouteImport.update({
  id: '/practice-supports',
  path: '/practice-supports',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocacyRoute = AdvocacyRouteImport.update({
  id: '/advocacy',
  path: '/advocacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/practice-supports': typeof PracticeSupportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/practice-supports': typeof PracticeSupportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/practice-supports': typeof PracticeSupportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advocacy'
    | '/connect'
    | '/events'
    | '/leadership'
    | '/news'
    | '/practice-supports'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advocacy'
    | '/connect'
    | '/events'
    | '/leadership'
    | '/news'
    | '/practice-supports'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advocacy'
    | '/connect'
    | '/events'
    | '/leadership'
    | '/news'
    | '/practice-supports'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvocacyRoute: typeof AdvocacyRoute
  ConnectRoute: typeof ConnectRoute
  EventsRoute: typeof EventsRoute
  LeadershipRoute: typeof LeadershipRoute
  NewsRoute: typeof NewsRoute
  PracticeSupportsRoute: typeof PracticeSupportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-supports': {
      id: '/practice-supports'
      path: '/practice-supports'
      fullPath: '/practice-supports'
      preLoaderRoute: typeof PracticeSupportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocacy': {
      id: '/advocacy'
      path: '/advocacy'
      fullPath: '/advocacy'
      preLoaderRoute: typeof AdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvocacyRoute: AdvocacyRoute,
  ConnectRoute: ConnectRoute,
  EventsRoute: EventsRoute,
  LeadershipRoute: LeadershipRoute,
  NewsRoute: NewsRoute,
  PracticeSupportsRoute: PracticeSupportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
